### ISSUE TITLE
Upgrade php overrides to match civicrm version 5.57.1

### ISSUE THREAD

**Issue by twomice** [twomice/com.joineryhq.estatweaks#5]
This extension uses php file overrides to modify civicrm core behavior (see the README). 
Every time the client upgrades civicrm, there's a good chance these files need to be updated to match core.

The directory at https://github.com/twomice/com.joineryhq.estatweaks/tree/master/CRM_PATCHES contains diffs of the overridden files between this extension and the given civicrm core version.

TODO:
* Update extension's files under https://github.com/twomice/com.joineryhq.estatweaks/tree/master/CRM to match civicrm 5.57.1 while preserving the appropraite customizations. See 837fa42120ad1fd4c0ae166cb6b8467563ecd87f for example.
* Update extension to reflect supported civicrm core version of 5.57.0 (see e1360423e1553640c7eadf315e8ef104a9313aa8 for example).

**Comment by andyburnsco** [comment]
See: https://github.com/twomice/com.joineryhq.estatweaks/pull/6

**Comment by twomice** [comment]
Fixed in c11c441 , tagged "v1.2-5.57.1". Thanks @andyburnsco !
